### ISSUE TITLE
Questions about use instructions

### ISSUE THREAD

**Issue by miabrahams** [LaraCraft93/e4rat-lite#1]
1. Should the kernel parameter in step 1 be `init=/usr/bin/e4rat-lite-collect`? 
2. On my system /sbin/init is just a symlink to /lib/systemd/systemd, is there a difference when writing e4rat-lite.conf? 
3. Do you think this is ready to use? I will accept a p=.05 chance of messing anything up.  =)

**Comment by calendulish** [comment]
1. Yes, must be. I already fix the README to reflect the correct file name (0881c2e).
2. There are no differences, you can safely use /sbin/init.
3. It's working, but has some minor bugs. It's not ready for a release, and I do not intend to create a new release. Hosnestly, I did some testing and e4rat-lite seems no longer necessary, unless you are running in an old and slow platform. It's useless to maintain a project that no longer arouses interest.
